routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
      return view('auth.login');
});

Auth::routes([
	'register' => false,
	
]);

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('rol','RolController');
Route::resource('autor','AutorController');
Route::resource('editorial','EditorialController');
Route::resource('libro','LibroController');
Route::resource('/usuario','UsuarioController');
Route::post('/porcentajea','PorcentajeController@aumentar')->name('porcentaje.aumentar');
Route::post('/porcentajed','PorcentajeController@disminuir')->name('porcentaje.disminuir');
Route::resource('aumentaindividual','AumentaController')->except(['create','store','destroy','show']);
Route::resource('restaindividual','RestaController')->except(['create','store','destroy','show']);

resources/views/autores/create.blade.php
@extends('layouts.template')

@section('titulo')
	Mantenimiento de Roles
@endsection

@section('content')

		
	
            <!-- MODALES -->

     <div class="col-lg-12 ">
              <div class="panel">
                  <div class="panel-heading">
                      <h3 class="panel-title bg-warning" style="color:#fff">Agregar Informacion del Autor</h3>
                  </div>
      
      
                  <!-- BASIC FORM ELEMENTS -->
              <form action="{{ route('autor.store') }}" onsubmit="return esfechavalida() " method="post" name="forma" class="panel-body form-horizontal form-padding">
                        @csrf
                        <!--Static-->
                        @include('autores.form',['mensaje'=> 'crear'])
                                    
                     </form>
                  <!--===================================================-->
                  <!-- END BASIC FORM ELEMENTS -->
      
      
              </div>
          </div>
		

@endsection

resources/views/autores/edit.blade.php
@extends('layouts.template')

@section('titulo')
	Mantenimiento de Roles
@endsection

@section('content')
@include("asset.validacion")	
	
         <div class="col-lg-12 ">
              <div class="panel">
                  <div class="panel-heading">
                      <h3 class="panel-title">Editar Informacion del Autor</h3>
                  </div>
      
      
                  <!-- BASIC FORM ELEMENTS -->
                  <!--===================================================-->
                  <form  action="{{ route('autor.update', $actualizar->id) }}" onsubmit="return esfechavalida() " name="forma" id="form1" method="post" class="panel-body form-horizontal form-padding">
                    @csrf
                    @method('PUT')
      
                 <div class="form-group">
                    <label class="col-md-3 control-label" for="demo-text-input">Nombres</label>
                        <div class="col-md-9">
                            <input type="text" name="hejr_nombres" value="{{ isset($actualizar->hejr_nombres) ? $actualizar->hejr_nombres : '' }}" id="demo-text-input" class="form-control" placeholder="Nombres">
                            @error('hejr_nombres')
                            <small class="help-block text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                    </div>
    
                    <!--Text Input-->
                    <div class="form-group">
                        <label class="col-md-3 control-label" for="demo-text-input">Apellidos</label>
                        <div class="col-md-9">
                            <input type="text" name="hejr_apellidos" value="{{ isset($actualizar->hejr_apellidos) ? $actualizar->hejr_apellidos : ''  }}" id="demo-text-input" class="form-control" placeholder="Apellidos">
                            @error('hejr_apellidos')
                            <small class="help-block text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                    </div>
    
                    <!--Email Input-->
                    <div class="form-group">
                        <label class="col-md-3 control-label" for="demo-email-input">Tipo DNI</label>
                        <div class="col-md-9">
                            <select name="hejr_tipo_dni" class="form-control">
                              <option>Seleccion tipo de dni</option>  
                              <option value="C" @if($actualizar->hejr_tipo_dni == 'C') selected=""  @endif) >Cedula Ciudadania</option>
                              <option value="P" @if($actualizar->hejr_tipo_dni == 'P') selected=""  @endif) >Pasaporte</option>
                            </select>
                             @error('hejr_tipo_dni')
                            <small class="help-block text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                    </div>

                     <div class="form-group">
                        <label class="col-md-3 control-label" for="demo-text-input">Dni</label>
                        <div class="col-md-9">
                            <input type="number" id="documento" onblur="validarDocumento()" name="hejr_dni"  onKeyPress="return soloNumeros(event)" value="{{ isset($actualizar->hejr_dni) ? $actualizar->hejr_dni : ''  }}" id="demo-text-input" class="form-control" placeholder="Ingrese Dni">
                             @error('hejr_dni')
                            <small class="help-block text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-3 control-label" for="demo-email-input">Sexo</label>
                        <div class="col-md-9">
                            <select name="hejr_sexo" class="form-control">
                              <option>Seleccion tipo de sexo</option> 
                              <option value="H" @if($actualizar->hejr_sexo == 'H') selected=""  @endif) >Hombre</option>
                              <option value="M" @if($actualizar->hejr_sexo == 'M') selected=""  @endif) >Mujer</option>
                            </select>
                            @error('hejr_sexo')
                            <small class="help-block text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                    </div>

                     <div class="form-group">
                        <label class="col-md-3 control-label" for="demo-text-input">Fecha Nacimiento</label>
                        <div class="col-md-9">
                            <input type="text" id="fecha" onblur="esfechavalida();" name="hejr_fecha_autor" value="{{ isset($actualizar->hejr_fecha_autor) ? $actualizar->hejr_fecha_autor : ''  }}"  id="demo-text-input" class="form-control" placeholder="Ingrese Email">
                            @error('hejr_fecha_autor')
                            <small class="help-block text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                    </div>
    

                     <div class="form-group">
                        <label class="col-md-3 control-label" for="demo-text-input">Email</label>
                        <div class="col-md-9">
                            <input type="text" name="hejr_email" value="{{ isset($actualizar->hejr_email) ? $actualizar->hejr_email : ''  }}"   id="demo-text-input" class="form-control" placeholder="Ingrese Email">
                            @error('hejr_email')
                            <small class="help-block text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-3 control-label" for="demo-email-input">Estado</label>
                        <div class="col-md-9">
                            <select name="hejr_estado" class="form-control">
                              <option>Seleccion de estado</option>  
                              <option value="A" @if($actualizar->hejr_estado == 'A') selected=""  @endif) >Activo</option>
                              <option value="I" @if($actualizar->hejr_estado == 'I') selected=""  @endif) >Inactivo</option>
                            </select>
                            @error('hejr_estado')
                            <small class="help-block text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                    </div>
          
                        
          
                        
          
                        
                         
           <div class="modal-footer">
                      <a href="{{ route('autor.index') }}" class="btn btn-default" type="button">Close</a>
                      <input type="submit" id="Guardar" class="btn btn-primary"  onclick="return confirm('Desea Actualizar?')" value="Actualizar Actor" name="">
                    
                   </div>
                  </form>
                  <!--===================================================-->
                  <!-- END BASIC FORM ELEMENTS -->
      
      
              </div>
          </div>  

   
		

@endsection

resources/views/autores/form.blade.php
@include("asset.validacion")



  					 <div class="form-group">
		                <label class="col-md-3 control-label" for="demo-text-input">Nombres</label>
		                    <div class="col-md-9">
		                        <input type="text"  id="nombres" value="{{ old('hejr_nombres') }}" name="hejr_nombres" value="{{ isset($actualizar->hejr_nombres) ? $actualizar->hejr_nombres : '' }}" id="demo-text-input" class="form-control" placeholder="Nombres">
		                        @error('hejr_nombres')
		                        <small class="help-block text-danger">{{ $message }}</small>
		                        @enderror
		                    </div>
		                </div>
		
		                <!--Text Input-->
		                <div class="form-group">
		                    <label class="col-md-3 control-label" for="demo-text-input">Apellidos</label>
		                    <div class="col-md-9">
		                        <input type="text"  id="apellidos" value="{{ old('hejr_apellidos') }}" name="hejr_apellidos" value="{{ isset($actualizar->hejr_apellidos) ? $actualizar->hejr_apellidos : ''  }}" id="demo-text-input" class="form-control" placeholder="Apellidos">
		                        @error('hejr_apellidos')
		                        <small class="help-block text-danger">{{ $message }}</small>
		                        @enderror
		                    </div>
		                </div>
		
		                <!--Email Input-->
		                <div class="form-group">
		                    <label class="col-md-3 control-label" for="demo-email-input">Tipo DNI</label>
		                    <div class="col-md-9">
		                        <select required="" name="hejr_tipo_dni" class="form-control">
		                        	<option value="">Seleccion tipo de dni</option>	
		                        	<option value="C" >Cedula Ciudadania</option>
		                        	<option value="P" >Pasaporte</option>
		                        </select>

		                        @error('hejr_tipo_dni')
									<span class="invalid-feedback d-block" role="alert">
										{{ $message }}
									</span>
									
								@enderror	
		                        
		                    </div>
		                </div>

		                 <div class="form-group">
		                    <label class="col-md-3  control-label" for="demo-text-input">Dni</label>
		                    <div class="col-md-9">
		                        <input type="number" value="{{ old('hejr_dni') }}" required="" id="documento" onblur="validarDocumento()" name="hejr_dni"  onKeyPress="return soloNumeros(event)" value="{{ isset($actualizar->hejr_dni) ? $actualizar->hejr_dni : ''  }}" id="demo-text-input" class="form-control" placeholder="Ingrese Dni">
		                         @error('hejr_dni')
		                        <small class="help-block text-danger">{{ $message }}</small>
		                        @enderror
		                    </div>
		                </div>

		                <div class="form-group">
		                    <label class="col-md-3 control-label" for="demo-email-input">Sexo</label>
		                    <div class="col-md-9">
		                        <select required="" name="hejr_sexo" class="form-control">
		                        	<option value="">Seleccion tipo de sexo</option>	
		                        	<option value="H">Hombre</option>
		                        	<option value="M">Mujer</option>
		                        </select>

	                           @error('hejr_sexo')
								<span class="invalid-feedback d-block" role="alert">
									{{ $message }}
								</span>
								@enderror	
		                       
		                    </div>
		                </div>

		                 <div class="form-group">
		                    <label class="col-md-3 control-label" for="demo-text-input">Fecha Nacimiento(yyyy-mm-dd)</label>
		                    <div class="col-md-9">
		                        <input type="text"  id="fecha" value="{{ old('hejr_fecha_autor') }}"  name="hejr_fecha_autor" value="{{ isset($actualizar->hejr_fecha_autor) ? $actualizar->hejr_fecha_autor : ''  }}"  id="demo-text-input" class="form-control" placeholder="Ingrese fecha">
		                        @error('hejr_fecha_autor')
		                        <small class="help-block text-danger">{{ $message }}</small>
		                        @enderror
		                    </div>
		                </div>
		

		                 <div class="form-group">
		                    <label class="col-md-3 control-label" for="demo-text-input">Email</label>
		                    <div class="col-md-9">
		                        <input type="text"  id="email" value="{{ old('hejr_email') }}" name="hejr_email" value="{{ isset($actualizar->hejr_email) ? $actualizar->hejr_email : ''  }}"   id="demo-text-input" class="form-control" placeholder="Ingrese Email">
		                        @error('hejr_email')
		                        <small class="help-block text-danger">{{ $message }}</small>
		                        @enderror
		                    </div>
		                </div>         
								              
								              
					               
					<div class="modal-footer">
	                    <a href="{{ route('autor.index') }}" class="btn btn-default" type="button">Close</a>
	                    <input type="submit"  class="btn btn-primary"  onclick="return confirm('Desea Agregar?')" value="Crear Actor" name="">
                    
               		 </div>

               		

               		

resources/views/autores/index.blade.php
@extends('layouts.template')

@section('titulo')
	Mantenimiento de Autores
@endsection

@section('content')

		
	 <div class="col-12">
          
            <!-- /.card -->

            <div class="card">
              <div class="card-header">
              <a href="{{ route('autor.create') }}" style="color:white;" class="btn btn-warning btn-rounded">Agregar</a>
              



                @if(Session::has('Mensaje'))  
                <div class="alert alert-info alert-dismissible mt-3">
                  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                  <h5><i class="icon fas fa-info"></i> Alert!</h5>
                  {{ Session::get('Mensaje') }}
                </div>
                @endif
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table id="example1" class="table table-bordered table-striped">
                  <thead>
                 <tr>
                      <th>Nombres y Apellidos</th>                                 
                      <th >DNI.</th>
                      <th >Sexo</th>
                      <th >Fecha Nacim.</th>
                      <th >Email</th>
                      <th >Estado</th>
                      <th>Eliminar</th>
                      <th>Editar</th>
                   
                      
                  </tr>
                  </thead>
              
                     <tbody>
                        @foreach($leer as $recorrer)
                        <tr>
                            <td>{{ $recorrer->hejr_nombres }} {{ $recorrer->hejr_apellidos }}</td>                               
                            <td>{{ $recorrer->hejr_dni }}</td>
                            <td>{{ $recorrer->hejr_sexo }}</td>
                            <td>{{ $recorrer->hejr_fecha_autor }}</td>
                            <td>{{ $recorrer->hejr_email }}</td>
                            <td>{{ $recorrer->hejr_estado }}</td>
                            <td>
                                <form action="{{ route('autor.destroy',$recorrer->id) }}" method="post">
                                    @csrf
                                    @method('DELETE')
                                      <button class="btn btn-danger btn-icon" onclick="return confirm('Desea Eliminar?')"><i class="fa fa-times-circle"></i></button>
                                </form> 
                                
                            </td>
                            <td>  
                             

                            
                           
                                <a class="btn btn-info btn-icon" href="{{ route('autor.edit',$recorrer->id) }}" ><i class="fa fa-pen-square"></i></a>
                            </td>

                        </tr>
                        @endforeach
                    </tbody>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
         
       

 
		

@endsection