routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
      return view('auth.login');
});

Auth::routes([
	'register' => false,
	
]);

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('rol','RolController');
Route::resource('autor','AutorController');
Route::resource('editorial','EditorialController');
Route::resource('libro','LibroController');
Route::resource('/usuario','UsuarioController');
Route::post('/porcentajea','PorcentajeController@aumentar')->name('porcentaje.aumentar');
Route::post('/porcentajed','PorcentajeController@disminuir')->name('porcentaje.disminuir');
Route::resource('aumentaindividual','AumentaController')->except(['create','store','destroy','show']);
Route::resource('restaindividual','RestaController')->except(['create','store','destroy','show']);

app/Libro.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Libro extends Model
{
	//LARAVEL ADMITIRA SOLO ESTOS CAMPOS EN  EL INGRESO DEL FORMULARIO PARA LA TABLA LIBRO EVITANDO ATAQUES SQL
    protected $fillable=['autor_id','editorial_id','hejr_ISBN','hejr_titulo','hejr_anio','hejr_precio_venta','hejr_otros_autores','hejr_estado'];

    //RELACION  DE UNO A MUCHOS

    public function autor(){
        return $this->belongsTo('App\Autor');
    }
    //RELACION  DE UNO A MUCHOS

    public function editorial(){
    	return $this->belongsTo('App\Editorial');
    }

}

app/Http/Controllers/LibroController.php
<?php

namespace App\Http\Controllers;


use App\Editorial;
use App\Autor;
use App\Libro;
use Illuminate\Http\Request;

class LibroController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    
   public function index()
    {
        $libro = Libro::all();
        $leer = $libro;

        $autor = Autor::all();
        $autores = $autor;

        $editorial = Editorial::all();
        $editoriales = $editorial;
        return view('libros.index',compact('leer','autores','editoriales'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
       
      $autor = Autor::all();
        $autores = $autor;

        $editorial = Editorial::all();
        $editoriales = $editorial;
        return view('libros.create',compact('autores','editoriales'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $datos = [
            'autor_id' => 'required | ',
            'editorial_id' => 'required',
            'hejr_ISBN' => 'required | unique:libros',
            'hejr_titulo' => 'required | min:5 | max:20 | string',
            'hejr_anio' => 'required | min: 4 | max:4| ',
            'hejr_precio_venta' => 'required|max:22|regex:/^-?[0-9]+(?:\.[0-9]{1,2})?$/',
            'hejr_otros_autores' => 'max:50|regex:/(^[A-Za-z0-9-, ]+$)+/'

        ];
      
      $this->validate($request,$datos);
        $datosLibro=request()->except('_token');

          $datosLibro['hejr_titulo'] = strtoupper($request->get('hejr_titulo'));
          $datosLibro['hejr_otros_autores'] = strtoupper($request->get('hejr_otros_autores'));

        
         
        Libro::insert($datosLibro);
       
        return redirect('libro')->with([
            'Mensaje' => 'Libro Agregado'
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Libro  $libro
     * @return \Illuminate\Http\Response
     */
    public function show(Libro $libro)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Libro  $libro
     * @return \Illuminate\Http\Response
     */
    public function edit( $id)
    {
        $autor = Autor::all();
        $autores = $autor;

        $editorial = Editorial::all();
        $editoriales = $editorial;

        $actualizar = Libro::findOrFail($id);
        return view('libros.edit',compact('actualizar','autores','editoriales'));
    
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Libro  $libro
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,  $id)
    {
       
        $datos = [
            'autor_id' => 'required | ',
            'editorial_id' => 'required',
            'hejr_ISBN' => 'required ',
            'hejr_titulo' => 'required | min:5 | max:20 | regex:/^[\pL\s\-]+$/u  |',
            'hejr_anio' => 'required | min: 4| max:4| alpha_num',
            'hejr_precio_venta' => 'required|max:22|regex:/^-?[0-9]+(?:\.[0-9]{1,2})?$/',
            'hejr_otros_autores' => 'max:50|regex:/(^[A-Za-z0-9-, ]+$)+/',
            'hejr_estado' => 'required'

        ];
      
      $this->validate($request,$datos);


       $datosLibro = request()->except('_token','_method'); 
       $datosLibro['hejr_titulo'] = strtoupper($request->get('hejr_titulo'));
       $datosLibro['hejr_otros_autores'] = strtoupper($request->get('hejr_otros_autores'));
        
       Libro::whereId($id)->update($datosLibro);
       
       return redirect("libro")->with([
        'Mensaje' => 'Libro actualizado'
       ]);    
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Libro  $libro
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Libro::whereId($id)->delete();
       
        return redirect('/libro')->with([
        'Mensaje' => 'Libro Eliminado',
         ]);
    }
}

resources/views/libros/PorcentajeAumentaLibro.blade.php
@extends('layouts.template')

@section('titulo')
	Mantenimiento de Libros
@endsection

@section('content')

		
   <div class="col-lg-12 ">
        <div class="panel">
            <div class="panel-heading">
                <h3 class="panel-title">Aumentar valor del libro {{ $actualizar->hejr_titulo }}
                  Valor $ {{ $actualizar->hejr_precio_venta }}
                </h3>

            </div>


       
            <!--===================================================-->
            <form  action="{{ route('aumentaindividual.update', $actualizar->id) }}" onsubmit="return validacionPorcentaje()"  method="post" class="panel-body form-horizontal form-padding">
              @csrf
              @method('PUT')
              @include('libros.formPorcentajeIndividual',['mensaje'=>'aumentar'])
             </div>
            </form>
            <!--===================================================-->
            <!-- END BASIC FORM ELEMENTS -->


        </div>
    </div>
		

@endsection

resources/views/libros/PorcentajeRestaLibro.blade.php
@extends('layouts.template')

@section('titulo')
	Mantenimiento de Libros
@endsection

@section('content')

		
  <div class="col-lg-12 ">
        <div class="panel">
            <div class="panel-heading">
                <h3 class="panel-title">Restar valor del libro {{ $actualizar->hejr_titulo }}
                  Valor $ {{ $actualizar->hejr_precio_venta }}
                </h3>

            </div>


       
            <!--===================================================-->
            <form  action="{{ route('restaindividual.update', $actualizar->id) }}"   method="post" class="panel-body form-horizontal form-padding">
              @csrf
              @method('PUT')
              @include('libros.formPorcentajeIndividual',['mensaje'=>'restar'])
             </div>
            </form>
            <!--===================================================-->
            <!-- END BASIC FORM ELEMENTS -->


        </div>
    </div>
		

@endsection

resources/views/libros/create.blade.php
@extends('layouts.template')

@section('titulo')
	Mantenimiento de Libros
@endsection

@section('content')

	 	
	   <div class="col-lg-12 ">
              <div class="panel">
                  <div class="panel-heading">
                      <h3 class="panel-title">Agregar Informacion del libro</h3>
                  </div>
      
      
             
           <form action="{{ route('libro.store') }}" onsubmit="return validacionLibro()" method="post" class="panel-body form-horizontal form-padding">
                        @csrf
                        <!--Static-->
                        @include('libros.form',['mensaje'=> 'crear'])
                                    
                     </form>
      
              </div>
          </div>






         
         
       

 
		

@endsection

resources/views/libros/edit.blade.php
@extends('layouts.template')

@section('titulo')
	Mantenimiento de Libros
@endsection

@section('content')

	 	
	  <div class="col-lg-12 ">
			        <div class="panel">
			            <div class="panel-heading">
			                <h3 class="panel-title bg-primary">Editar Informacion del libro</h3>
			            </div>
			
			
			       
			            <!--===================================================-->
			            <form  action="{{ route('libro.update', $actualizar->id) }}"  method="post" class="panel-body form-horizontal form-padding">
			            	@csrf
			            	@method('PUT')


			         
			     


		           <div class="form-group">
	                <label class="col-md-3 control-label" for="demo-text-input">Autor</label>
	                    <div class="col-md-9">
	                        <select class="form-control" name="autor_id">
	                        	@forelse($autores as $autor)
	                        	
	                        		<option value="{{ $autor->id }}" @if($autor->id == $actualizar->autor_id) selected="" @endif>{{ $autor->hejr_nombres. ' '.$autor->hejr_apellidos }}</option>
	                        	@empty
	                        	<span class="text-danger">No se encontraron roles</span>

	                        	@endforelse
	                        </select>
	                        @error('autor_id')
	                        <small class="help-block text-danger">{{ $message }}</small>
	                        @enderror
	                    </div>
	            	 </div>	


			   
		             <div class="form-group">
		                <label class="col-md-3 control-label" for="demo-text-input">Seleccione Editorial</label>
		                    <div class="col-md-9">
		                        <select class="form-control" name="editorial_id">
		                        	@forelse($editoriales as $editorial)
		                        	
		                        		<option value="{{ $editorial->id }}" @if($editorial->id == $actualizar->editorial_id) selected="" @endif>{{ $editorial->hejr_nombre }}</option>


		                        	@empty
		                        	<span class="text-danger">No se encontraron roles</span>

		                        	@endforelse
		                        </select>
		                        @error('editorial_id')
		                        <small class="help-block text-danger">{{ $message }}</small>
		                        @enderror
		                    </div>
		             </div>

			
			            <div class="form-group">
			                	<label class="col-md-3 control-label" for="demo-text-input">ISBN</label>
			                    <div class="col-md-9">
			                        <input type="text" required="" name="hejr_ISBN" id="isbn" onblur="run()" value="{{ isset($actualizar->hejr_ISBN) ? $actualizar->hejr_ISBN : '' }}" id="demo-text-input" class="form-control" placeholder="Ingrese ISBN">
			                        @error('hejr_ISBN')
			                        <small class="help-block text-danger">{{ $message }}</small>
			                        @enderror
			                    </div>
		                </div>
		
		             	

		                 <div class="form-group">
		                    <label class="col-md-3 control-label" for="demo-text-input">Titulo</label>
		                    <div class="col-md-9">
		                        <input type="text" id="titulo" name="hejr_titulo" value="{{ isset($actualizar->hejr_titulo) ? $actualizar->hejr_titulo : ''  }}"   id="demo-text-input" class="form-control" placeholder="Ingrese titulo">
		                        @error('hejr_titulo')
		                        <small class="help-block text-danger">{{ $message }}</small>
		                        @enderror
		                    </div>
		                </div>

		                 <div class="form-group">
		                    <label class="col-md-3 control-label" for="demo-text-input">Año</label>
		                    <div class="col-md-9">
		                        <input type="text" id="anio" name="hejr_anio" value="{{ isset($actualizar->hejr_anio) ? $actualizar->hejr_anio : ''  }}"   id="demo-text-input" class="form-control" placeholder="Ingrese Año del libro">
		                        @error('hejr_anio')
		                        <small class="help-block text-danger">{{ $message }}</small>
		                        @enderror
		                    </div>
		                </div>

		                 <div class="form-group">
		                    <label class="col-md-3 control-label" for="demo-text-input">Precio de venta</label>
		                    <div class="col-md-9">
		                        <input type="text" id="precio" name="hejr_precio_venta" value="{{ isset($actualizar->hejr_precio_venta) ? $actualizar->hejr_precio_venta : ''  }}"   id="demo-text-input" class="form-control" placeholder="Ingrese Precio de venta">
		                        @error('hejr_precio_venta')
		                        <small class="help-block text-danger">{{ $message }}</small>
		                        @enderror
		                    </div>
		                </div>

		                   <div class="form-group">
		                    <label class="col-md-3 control-label" for="demo-text-input">Otros autores</label>
		                    <div class="col-md-9">
		                        <input  name="hejr_otros_autores"  style="resize: none" value="{{ isset($actualizar->hejr_otros_autores) ? $actualizar->hejr_otros_autores : ''  }}"   id="demo-text-input" class="form-control" placeholder="Ingrese otros autores">
		                        @error('hejr_otros_autores')
		                        <small class="help-block text-danger">{{ $message }}</small>
		                        @enderror
		                    </div>
		                </div>

		                <div class="form-group">
		                    <label class="col-md-3 control-label" for="demo-email-input">Estado</label>
		                    <div class="col-md-9">
		                        <select name="hejr_estado" class="form-control">
		                        	<option>Seleccion de estado</option>	
		                        	<option value="A" @if($actualizar->hejr_estado == 'A') selected=""  @endif) >Activo</option>
		                        	<option value="I" @if($actualizar->hejr_estado == 'I') selected=""  @endif) >Inactivo</option>
		                        </select>
		                        @error('hejr_estado')
		                        <small class="help-block text-danger">{{ $message }}</small>
		                        @enderror
		                    </div>
		                </div>
					
					              
					
					              
					
					              
					               
					 <div class="modal-footer">
	                    <a href="{{ route('libro.index') }}" class="btn btn-default" type="button">Close</a>
	                    <input type="submit" class="btn btn-primary"  onclick="return confirm('Desea Actualizar?')" value="Actualizar Libro" name="">
                    
               		 </div>
			            </form>
			            <!--===================================================-->
			            <!-- END BASIC FORM ELEMENTS -->
			
			
			        </div>
			    </div>





         
         
       

 
		

@endsection

resources/views/libros/form.blade.php
				<div class="form-group">
	                <label class="col-md-3 control-label" for="demo-text-input">Autor</label>
	                    <div class="col-md-9">
	                        <select class="form-control" required="" name="autor_id">
	                        	@forelse($autores as $autor)
	                        	
	                        		<option value="{{ $autor->id }}">{{ $autor->hejr_nombres .' '. $autor->hejr_apellidos}}</option>
	                        	@empty
	                        	<span class="text-danger">No se encontraron roles</span>

	                        	@endforelse
	                        </select>
	                        @error('autor_id')
	                        <small class="help-block text-danger">{{ $message }}</small>
	                        @enderror
	                    </div>
	             </div>

	             <div class="form-group">
	                <label class="col-md-3 control-label" for="demo-text-input">Editorial</label>
	                    <div class="col-md-9">
	                        <select class="form-control" required="" name="editorial_id">
	                        	@forelse($editoriales as $editorial)
	                        	
	                        		<option value="{{ $editorial->id }}">{{ $editorial->hejr_nombre }}</option>
	                        	@empty
	                        	<span class="text-danger">No se encontraron roles</span>

	                        	@endforelse
	                        </select>
	                        @error('editorial_id')
	                        <small class="help-block text-danger">{{ $message }}</small>
	                        @enderror
	                    </div>
	             </div>


	          
				<div class="form-group">
               		 <label class="col-md-3 control-label" for="demo-text-input">ISBN</label>
               		  
                    <div class="col-md-9">
                        <input type="text" name="hejr_ISBN"  required="" value="{{ old('hejr_ISBN') }}"  id="isbn" onblur="run()"   class="form-control" placeholder="Ingrese ISBN">
                        @error('hejr_ISBN')
                        <small class="help-block text-danger">{{ $message }}</small>
                        @enderror
                    </div>
                </div>

                <div class="form-group">
               		 <label class="col-md-3 control-label" for="demo-text-input">Titulo</label>
                    <div class="col-md-9">
                        <input type="text" name="hejr_titulo"  id="titulo" value="{{ old('hejr_titulo') }}" class="form-control" placeholder="Ingrese el titulo del libro">
                        @error('hejr_titulo')
                        <small class="help-block text-danger">{{ $message }}</small>
                        @enderror
                    </div>
                </div>


                <div class="form-group">
               		 <label class="col-md-3 control-label" for="demo-text-input">Año</label>
                    <div class="col-md-9">
                        <input type="number" name="hejr_anio"  value="{{ old('hejr_anio') }}" id="anio" class="form-control" placeholder="Ingrese el año del libro">
                        @error('hejr_anio')
                        <small class="help-block text-danger">{{ $message }}</small>
                        @enderror
                    </div>
                </div>


                
		             
	            <div class="form-group">
	                    <label class="col-md-3 control-label" for="demo-text-input">Precio de venta</label>
	                    <div class="col-md-9">
	                        <input type="text" name="hejr_precio_venta" value="{{ old('hejr_precio_venta') }}"    id="precio" class="form-control" placeholder="Ingrese precio de venta">
	                        @error('hejr_precio_venta')
	                        <small class="help-block text-danger">{{ $message }}</small>
	                        @enderror
	                    </div>
	            </div>
					
			  <div class="form-group">
                    <label class="col-md-3 control-label"  for="demo-text-input">Otros autores</label>
                    <div class="col-md-9">
                        <input  name="hejr_otros_autores"  value="No hay"  id="autor" class="form-control" placeholder="Ingrese otros autores">
                        @error('hejr_otros_autores')
                        <small class="help-block text-danger">{{ $message }}</small>
                        @enderror
                    </div>
	            </div>
						              
					 
					              
					
					              
				               
				 <div class="modal-footer">
	                    <a href="{{ route('libro.index') }}" class="btn btn-default" type="button">Close</a>
	                    <input type="submit" class="btn btn-primary"  onclick="return confirm('Desea Agregar?')" value="Crear Libro" name="">
                    
               	</div>

resources/views/libros/formPorcentaje.blade.php
  
		<div class="form-group">
       		 <label class="col-md-4 control-label" for="demo-text-input">Porcentaje(Valido 10, 20 etc)</label>
            <div class="col-md-8">
                <input type="number"   name="hejr_porcentaje"  required=""   id="porcentaje" class="form-control" placeholder="Ingrese Procentaje">
                @error('hejr_porcentaje')
                <small class="help-block text-danger">{{ $message }}</small>
                @enderror
            </div>
        </div>

         <div class="modal-footer">
            <button data-dismiss="modal" class="btn btn-default" type="button">Close</button>
            <input type="submit"  class="btn btn-primary"  value="Aumentar Porcentaje a todos los  libros" name="">
        
   		 </div>

        

      

resources/views/libros/formPorcentajeIndividual.blade.php
        <div class="form-group">
             <label class="col-md-4 control-label" for="demo-text-input">Porcentaje(Valido 10, 20 etc)</label>
            <div class="col-md-8">
                <input type="text" required="" name="hejr_porcentaje"  id="porcentaje"  class="form-control" placeholder="Ingrese Procentaje">
                @error('hejr_porcentaje')
                <small class="help-block text-danger">{{ $message }}</small>
                @enderror
            </div>

             <div class="col-md-8">
                <input type="hidden" name="hejr_titulo"  value="{{ $actualizar->hejr_titulo }}" id="demo-text-input" class="form-control" placeholder="Ingrese Procentaje">
                @error('hejr_titulo')
                <small class="help-block text-danger">{{ $message }}</small>
                @enderror
            </div>

        </div>

         <div class="modal-footer">
            <a href="{{ route('libro.index') }}" class="btn btn-default" type="button">Close</a>
            <input type="submit" onclick="return confirm('Desea cambiar el porcentaje?')" class="btn btn-primary"  value="{{ $mensaje === 'aumentar' ? 'Aumentar ' : ' Disminuir' }} Porcentaje del libro" name="">
        
        </div>

resources/views/libros/index.blade.php
@extends('layouts.template')

@section('titulo')
	Mantenimiento de Libros
@endsection

@section('content')

		
	 <div class="col-12">
          
            <!-- /.card -->

            <div class="card">
              <div class="card-header">
                 <a  href="{{ route('libro.create') }}"  class="btn btn-warning btn-rounded " style="color: white">Agregar</a>

                 @auth 
                    @if(Auth::user()->rol->hejr_nombre == 'ADMINISTRADOR') 
                      <button data-target="#modal-aumentar" data-toggle="modal" class="btn btn-info btn-rounded">Porcentaje +</button>

                      <button data-target="#modal-disminuir" data-toggle="modal" class="btn btn-danger btn-rounded">Porcentaje -</button>
                    @endif
                  @endauth   

                @if(Session::has('Mensaje'))  
                  <div class="alert alert-info alert-dismissible mt-3">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    <h5><i class="icon fas fa-info"></i> Alert!</h5>
                    {{ Session::get('Mensaje') }}
                  </div>
                @endif
                
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table id="example1" class="table table-bordered table-striped">
                  <thead>
                  <tr>
                      <th>Autor</th>  
                      <th>Editorial</th>                                
                      <th >ISBN</th>
                      <th >Titulo</th>
                      <th >Año</th>
                      <th >Precio de venta</th>
                       <th >Otros autores</th>
                      <th>Eliminar</th>
                      <th>Editar</th>
                      @auth @if(Auth::user()->rol->hejr_nombre == 'ADMINISTRADOR')

                       <th>Porcentaje</th>
                      @endif
                      @endauth
                   
                      
                  </tr>
                  </thead>
              
                    <tbody>
                          @foreach($leer as $recorrer)
                                    <tr>
                                        <td> {{ isset($recorrer->autor->hejr_nombres) ? $recorrer->autor->hejr_nombres .' '. $recorrer->autor->hejr_apellidos   : '' }} 
                                        </td>
                                        <td>{{ isset($recorrer->editorial->hejr_nombre) ? $recorrer->editorial->hejr_nombre : '' }}
                                        </td>

                                        <td>{{ $recorrer->hejr_ISBN }}</td>
                                        <td>{{ $recorrer->hejr_titulo }}</td>
                                        <td>{{ $recorrer->hejr_anio }}</td>
                                        <td>{{ $recorrer->hejr_precio_venta }}</td>
                                        <td>{{ $recorrer->hejr_otros_autores }}</td>
                                        <td>
                                            <form action="{{ route('libro.destroy',$recorrer->id) }}" method="post">
                                                @csrf
                                                @method('DELETE')
                                                  <button class="btn btn-danger btn-icon" onclick="return confirm('Desea Eliminar?')"><i class="fa fa-times-circle"></i></button>
                                            </form> 
                                            
                                        </td>
                                        <td>  
                                                                               
                                            <a class="btn btn-info btn-icon" href="{{ route('libro.edit',$recorrer->id) }}"><i class="fa fa-pen-square"></i></a>
                                        </td>

                                       @if(Auth::user()->rol->hejr_nombre == 'ADMINISTRADOR')

                                        <td>
                                            <a href="{{ route('aumentaindividual.edit',$recorrer->id) }}" class="btn btn-link btn-icon icon-lg fa fa-chevron-up">
                                                
                                            </a>
                                        @if($recorrer->hejr_precio_venta > 1)    
                                            <a href="{{ route('restaindividual.edit',$recorrer->id) }}" class="btn btn-link btn-icon icon-lg fa fa-chevron-down">
                                        @else
                                            <span class="text-danger">No disminuir precio</span>        
                                        @endif        
                                            </a>
                                        </td>
                                    @endif 
                                   
                                    </tr>
                                    @endforeach
                    </tbody>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
         
       

      <!-- MODALES -->

  

    <div class="modal fade" id="modal-aumentar" role="dialog" tabindex="-1" aria-labelledby="demo-default-modal" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">

                <!--Modal header-->
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><i class="pci-cross pci-circle"></i></button>
                    <h4 class="modal-title text-center">Aumentar porcentaje a todos los Libros </h4>
                </div>

                <!--Modal body-->
                <div class="modal-body">
                     <form action="{{ route('porcentaje.aumentar') }}"  method="post" class="panel-body form-horizontal form-padding">
                        @csrf
                        <!--Static-->
                        @include('libros.formPorcentaje')
                                    
                     </form>
                   
                </div>

                <!--Modal footer-->
             
            </div>
        </div>
    </div>

     <div class="modal fade" id="modal-disminuir" role="dialog" tabindex="-1" aria-labelledby="demo-default-modal" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">

                <!--Modal header-->
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><i class="pci-cross pci-circle"></i></button>
                    <h4 class="modal-title text-center">Disminuir porcentaje a todos los Libros </h4>
                </div>

                <!--Modal body-->
                <div class="modal-body">
                     <form action="{{ route('porcentaje.disminuir') }}" onsubmit="return validacionPorcentaje()"  method="post" class="panel-body form-horizontal form-padding">
                        @csrf
                        <!--Static-->
                        @include('libros.formPorcentajeDisminuir')
                                    
                     </form>
                   
                </div>

                <!--Modal footer-->
             
            </div>
        </div>
    </div>

		

@endsection