routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
      return view('auth.login');
});

Auth::routes([
	'register' => false,
	
]);

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('rol','RolController');
Route::resource('autor','AutorController');
Route::resource('editorial','EditorialController');
Route::resource('libro','LibroController');
Route::resource('/usuario','UsuarioController');
Route::post('/porcentajea','PorcentajeController@aumentar')->name('porcentaje.aumentar');
Route::post('/porcentajed','PorcentajeController@disminuir')->name('porcentaje.disminuir');
Route::resource('aumentaindividual','AumentaController')->except(['create','store','destroy','show']);
Route::resource('restaindividual','RestaController')->except(['create','store','destroy','show']);

app/Http/Controllers/UsuarioController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use App\Rol;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Auth;

class UsuarioController extends Controller
{
   public function __construct()
    {
        $this->middleware('auth');
    }
    
    public function index()
    {

       
        if(Auth::user()->rol->hejr_nombre == 'ADMINISTRADOR'){
                $user = User::all();
                $leer = $user;

                $role = Rol::all();
                $roles = $role;
                return view('usuarios.index',compact('leer','roles'));  
        }else{
            return "No eres Administrador";
        }
       
      

       
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $role = Rol::all();
        $roles = $role;
        return view('usuarios.create',compact('roles')); 
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
       $datos = [
            'rol_id' => 'required | ',
            'name' => 'required | min:5 | max:30  | regex:/^[\pL\s\-]+$/u',
            'email' => 'required | email | string | unique:users',
            'password' => 'required | string | min:8 | max:30',
            'dni' => 'required | alpha_num | max:15 | min:10 | unique:users',
            'sexo' => 'required',
            'direccion' => 'max:50| min:6 | string',
            'telefono' => 'required | min:7 | max:15 | alpha_num' ,
            'fecha_nacimiento' => 'required | date',
            'foto' => 'required | image'

        ];
      
      $this->validate($request,$datos);
        $datosUsuario=request()->except('_token');
        $datosUsuario['name']= strtoupper($request->get('name'));
         $datosUsuario['email']= strtoupper($request->get('email'));
          $datosUsuario['direccion']= strtoupper($request->get('direccion'));

         if($request->hasFile('foto')){
            $datosUsuario['foto']=$request->file('foto')->store('uploads','public');
        }

        
        User::insert($datosUsuario);
       
        return redirect('/usuario')->with([
            'Mensaje' => 'Usuario Agregado'
        ]);
    
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
       

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $role = Rol::all();
        $roles = $role;

        $actualizar = User::findOrFail($id);
        return view('usuarios.edit',compact('actualizar','roles'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

      $datos = [
            'rol_id' => 'required | ',
            'name' => 'required | min:5 | max:30  | regex:/^[\pL\s\-]+$/u',
            'email' => 'required | email | string | ',
            'password' => 'required | string | min:8 | max:30',
            'dni' => 'required | alpha_num | max:15 | min:10 |',
            'sexo' => 'required',
            'direccion' => 'max:50| min:6 | string',
            'telefono' => 'required | min:7 | max:15 | alpha_num' ,
            'fecha_nacimiento' => 'required | date',
          
            'estado' => 'required'

        ];
      
      $this->validate($request,$datos);


       $datosUsuario = request()->except('_token','_method'); 
       $datosUsuario['name']= strtoupper($request->get('name'));
         $datosUsuario['email']= strtoupper($request->get('email'));
          $datosUsuario['direccion']= strtoupper($request->get('direccion'));
          
        if($request->hasFile('foto')){

            $usuario = User::findOrFail($id);

            Storage::delete('public/'.$usuario->foto);
            
            $datosUsuario['foto']=$request->file('foto')->store('uploads','public');
        }
         User::whereId($id)->update($datosUsuario);
       
       return redirect("usuario")->with([
        'Mensaje' => 'Usuario actualizado'
       ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
       $usuario = User::findOrFail($id);

       if(Storage::delete('public/'.$usuario->foto)){
            User::whereId($id)->delete();
       }



        

         return redirect('/usuario')->with([
        'Mensaje' => 'Usuario Eliminado',
    ]);
    }
}

resources/views/usuarios/create.blade.php
@extends('layouts.template')

@section('titulo')
	Mantenimiento de Usuarios
@endsection

@section('content')

		
	 <div class="col-lg-12 ">
        <div class="panel">
            <div class="panel-heading">
                <h3 class="panel-title">Agregar Informacion del usuario</h3>
            </div>


            <!-- BASIC FORM ELEMENTS -->
            <!--===================================================-->
         <form action="{{ route('usuario.store') }}" onsubmit="return esfechavalida()" method="post" enctype="multipart/form-data" class="panel-body form-horizontal form-padding">
                  @csrf
                  <!--Static-->
                  @include('usuarios.form',['mensaje'=> 'crear'])
                              
               </form>
            <!--===================================================-->
            <!-- END BASIC FORM ELEMENTS -->


        </div>
    </div>
 
		

@endsection

resources/views/usuarios/edit.blade.php
@extends('layouts.template')

@section('titulo')
	Mantenimiento de Usuarios
@endsection

@section('content')
@include("asset.validacion")
		
	 <div class="col-lg-12 ">
              <div class="panel">
                  <div class="panel-heading">
                      <h3 class="panel-title">Editar Informacion del usuario</h3>
                  </div>
      
      
                  <!-- BASIC FORM ELEMENTS -->
                  <!--===================================================-->
              <form  action="{{ route('usuario.update', $actualizar->id) }}" onsubmit="return esfechavalida()" enctype="multipart/form-data" method="post" class="panel-body form-horizontal form-padding">
                @csrf
                @method('PUT')
      



               <div class="form-group">
                  <label class="col-md-3 control-label" for="demo-text-input">Rol</label>
                      <div class="col-md-9">
                          <select class="form-control" required="" name="rol_id">
                            @forelse($roles as $rol)
                            
                              <option value="{{ $rol->id }}" @if($rol->id == $actualizar->rol_id) selected="" @endif>{{ $rol->hejr_nombre }}</option>
                            @empty
                            <span class="text-danger">No se encontraron roles</span>

                            @endforelse
                          </select>
                          @error('rol_id')
                          <small class="help-block text-danger">{{ $message }}</small>
                          @enderror
                      </div>
                 </div>     


             

                




             <div class="form-group">
                    <label class="col-md-3 control-label" enctype="multipart/form-data" for="demo-text-input">Nombres - Apellidos</label>
                        <div class="col-md-9">
                            <input type="text" name="name" value="{{ $actualizar->name }}"   id="demo-text-input" class="form-control" placeholder="Ingrese nombre y apellidos">
                            @error('name')
                            <small class="help-block text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                 </div>

                 <div class="form-group">
                        <label class="col-md-3 control-label" for="demo-text-input">Email</label>
                        <div class="col-md-9">
                            <input type="text" name="email" value="{{ $actualizar->email }}"    id="demo-text-input" class="form-control" placeholder="Ingrese Email">
                            @error('email')
                            <small class="help-block text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                </div>

                  <div class="form-group">
                    <label class="col-md-3 control-label" for="demo-text-input">Password</label>
                        <div class="col-md-9">
                            <input type="password" name="password" value="{{ $actualizar->password }}"   id="demo-text-input" class="form-control" placeholder="Ingrese password">
                            @error('password')
                            <small class="help-block text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                 </div>
    


           <div class="form-group">
                    <label class="col-md-3 control-label" for="demo-text-input">Cedula</label>
                        <div class="col-md-9">
                            <input type="text" name="dni" required="" onBlur="validarDocumento()" onKeyPress="return soloNumeros(event)"  id="documento" value="{{ $actualizar->dni }}"    class="form-control" placeholder="Ingrese cedula">
                            @error('dni')
                            <small class="help-block text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                 </div>

                 <div class="form-group">
                    <label class="col-md-3 control-label" for="demo-text-input">Direccion</label>
                        <div class="col-md-9">
                            <input type="text" name="direccion" value="{{ $actualizar->direccion }}"   id="demo-text-input" class="form-control" placeholder="Ingrese direccion">
                            @error('direccion')
                            <small class="help-block text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                 </div>

                 <div class="form-group">
                    <label class="col-md-3 control-label" for="demo-text-input">Telefono</label>
                        <div class="col-md-9">
                            <input type="text" name="telefono" value="{{ $actualizar->telefono }}"  id="demo-text-input" onKeyPress="return soloNumeros(event)" class="form-control" placeholder="Ingrese telefono">
                            @error('telefono')
                            <small class="help-block text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                 </div>

                   <div class="form-group">
                        <label class="col-md-3 control-label" for="demo-email-input">Sexo</label>
                        <div class="col-md-9">
                            <select name="sexo" class="form-control">
                              <option>Seleccion tipo de sexo</option> 
                              <option value="H" @if($actualizar->sexo == 'H') selected=""  @endif) >Hombre</option>
                              <option value="M" @if($actualizar->sexo == 'M') selected=""  @endif) >Mujer</option>
                            </select>
                            @error('sexo')
                            <small class="help-block text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                    </div>

                     <div class="form-group">
                        <label class="col-md-3 control-label" for="demo-text-input">Fecha Nacimiento</label>
                        <div class="col-md-9">
                            <input type="text" name="fecha_nacimiento" value="{{ $actualizar->fecha_nacimiento }}"    id="demo-text-input" class="form-control">
                            @error('fecha_nacimiento')
                            <small class="help-block text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-3 control-label">Seleccione Foto</label>

                         <div class="col-md-9" >
                          <div class="row">
                            <div class="col-md-4" >
                                <span class="pull-left btn btn-primary btn-file ">
                                Cargar Foto... <input type="file" name="foto">
                                </span>
                            </div>
                            <div class="col-md-8">
                                 @if(isset($actualizar->foto))
      
                    <img style="position: relative; left: 10px;" src="{{ asset('storage').'/'.$actualizar->foto }}" width="100">
                    @endif
                  </div>
                </div>  
                       </div>
                       

                            
                        @error('foto')
                             <small class="help-block text-danger">{{ $message }}</small>
                          @enderror
                    </div>

                    <div class="form-group">
                        <label class="col-md-3 control-label" for="demo-email-input">Estado</label>
                        <div class="col-md-9" >
                            <select name="estado" class="form-control">
                              <option>Seleccion de estado</option>  
                              <option value="A" @if($actualizar->estado == 'A') selected=""  @endif) >Activo</option>
                              <option value="I" @if($actualizar->estado == 'I') selected=""  @endif) >Inactivo</option>
                            </select>
                            @error('estado')
                            <small class="help-block text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                    </div>
                        
          
                        
          
                        
                         
           <div class="modal-footer">
                      <a href="{{ route('usuario.index') }}" class="btn btn-default" type="button">Close</a>
                      <input type="submit" class="btn btn-primary"  onclick="return confirm('Desea Actualizar?')" value="Actualizar Usuario" name="">
                    
                   </div>
                  </form>
                  <!--===================================================-->
                  <!-- END BASIC FORM ELEMENTS -->
      
      
              </div>
          </div>
 
		

@endsection

resources/views/usuarios/form.blade.php
@include("asset.validacion")

  					<div class="form-group">
		                <label class="col-md-3 control-label" for="demo-text-input">Rol</label>
		                    <div class="col-md-9">
		                        <select class="form-control" required name="rol_id">
		                        	@forelse($roles as $rol)
		                        		
		                        		<option value="{{ $rol->id }}">{{ $rol->hejr_nombre }}</option>
		                        	@empty
		                        	<span class="text-danger">No se encontraron roles</span>

		                        	@endforelse
		                        </select>
		                        @error('rol_id')
		                        <small class="help-block text-danger">{{ $message }}</small>
		                        @enderror
		                    </div>
		             </div>




  					 <div class="form-group">
		                <label class="col-md-3 control-label" for="demo-text-input">Nombres - Apellidos</label>
		                    <div class="col-md-9">
		                        <input type="text" name="name"  value="{{ old('name') }}" id="demo-text-input" class="form-control" placeholder="Ingrese nombre y apellidos">
		                        @error('name')
		                        <small class="help-block text-danger">{{ $message }}</small>
		                        @enderror
		                    </div>
		             </div>

		             <div class="form-group">
		                    <label class="col-md-3 control-label" for="demo-text-input">Email</label>
		                    <div class="col-md-9">
		                        <input type="text" name="email" value="{{ old('email') }}"   id="demo-text-input" class="form-control" placeholder="Ingrese Email">
		                        @error('email')
		                        <small class="help-block text-danger">{{ $message }}</small>
		                        @enderror
		                    </div>
		            </div>

		              <div class="form-group">
		                <label class="col-md-3 control-label" for="demo-text-input">Password</label>
		                    <div class="col-md-9">
		                        <input type="password" name="password"  id="demo-text-input" class="form-control" placeholder="Ingrese password">
		                        @error('password')
		                        <small class="help-block text-danger">{{ $message }}</small>
		                        @enderror
		                    </div>
		             </div>
		


					 <div class="form-group">
		                <label class="col-md-3 control-label" for="demo-text-input">Cedula</label>
		                    <div class="col-md-9">
		                        <input type="text" name="dni" required=""  value="{{ old('dni') }}" id="documento" onBlur="validarDocumento()" onKeyPress="return soloNumeros(event)"  id="documento" class="form-control" placeholder="Ingrese cedula">
		                        @error('dni')
		                        <small class="help-block text-danger">{{ $message }}</small>
		                        @enderror
		                    </div>
		             </div>

		             <div class="form-group">
		                <label class="col-md-3 control-label" for="demo-text-input">Direccion</label>
		                    <div class="col-md-9">
		                        <input type="text" name="direccion" value="{{ old('direccion') }}"  id="demo-text-input" class="form-control" placeholder="Ingrese direccion">
		                        @error('direccion')
		                        <small class="help-block text-danger">{{ $message }}</small>
		                        @enderror
		                    </div>
		             </div>

		             <div class="form-group">
		                <label class="col-md-3 control-label" for="demo-text-input">Telefono</label>
		                    <div class="col-md-9">
		                        <input type="text" name="telefono" value="{{ old('telefono') }}"  id="demo-text-input" class="form-control" onKeyPress="return soloNumeros(event)" placeholder="Ingrese telefono">
		                        @error('telefono')
		                        <small class="help-block text-danger">{{ $message }}</small>
		                        @enderror
		                    </div>
		             </div>

		               <div class="form-group">
		                    <label class="col-md-3 control-label" for="demo-email-input">Sexo</label>
		                    <div class="col-md-9">
		                        <select name="sexo" class="form-control">
		                        	<option value="">Seleccion tipo de sexo</option>	
		                        	<option value="H">Hombre</option>
		                        	<option value="M">Mujer</option>
		                        </select>
		                        @error('sexo')
		                        <small class="help-block text-danger">{{ $message }}</small>
		                        @enderror
		                    </div>
		                </div>

		                 <div class="form-group">
		                    <label class="col-md-3 control-label" for="demo-text-input">Fecha Nacimiento</label>
		                    <div class="col-md-9">
		                        <input type="text" name="fecha_nacimiento" value="{{ old('fecha_nacimiento') }}" placeholder="2001/05/15" id="fecha" class="form-control">
		                        @error('fecha_nacimiento')
		                        <small class="help-block text-danger">{{ $message }}</small>
		                        @enderror
		                    </div>
		                </div>

		                  <div class="form-group">
			                    <label class="col-md-3 control-label">Seleccione Foto</label>
			                    <div class="col-md-9">
			                        <span class="pull-left btn btn-primary btn-file">
			                        Cargar Foto... <input type="file" name="foto">
			                        </span>
			                    </div>

			                    @error('foto')
		                       		 <small class="help-block text-danger">{{ $message }}</small>
		                        @enderror
			                </div>

		
		         
							              
					
					           
					
					              
					               
					 <div class="modal-footer">
	                    <a href="{{ route('usuario.index') }}" class="btn btn-default" type="button">Close</a>
	                    <input type="submit" class="btn btn-primary"  onclick="return confirm('Desea Agregar?')" value="Crear Usuario" name="">
                    
               		 </div>

resources/views/usuarios/index.blade.php
@extends('layouts.template')

@section('titulo')
	Mantenimiento de Usuarios
@endsection

@section('content')

		
	 <div class="col-12">
          
            <!-- /.card -->

            <div class="card">
              <div class="card-header">
                <a href="{{ route('usuario.create') }}" class="btn btn-warning btn-rounded" style="color:white;">Agregar</a> 

                @if(Session::has('Mensaje'))  
                  <div class="alert alert-info alert-dismissible mt-3">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    <h5><i class="icon fas fa-info"></i> Alert!</h5>
                    {{ Session::get('Mensaje') }}
                  </div>
                @endif

              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table id="example1" class="table table-bordered table-striped">
                  <thead>
                  <tr>
                    <th>Rol</th>                                 
                    <th >Nombres</th>
                    <th >Email</th>
                    <th>Dni</th>
                    <th>Sexo</th>
                    <th>Direccion</th>
                    <th>Telefono</th>
                    <th>Estado</th>
                    <th>Foto</th>
                    <th>Eliminar</th>
                    <th>Editar</th>
                   
                      
                  </tr>
                  </thead>
              
                    <tbody>
                          @foreach($leer as $recorrer)
                              <tr>
                                  <td>{{ isset($recorrer->rol->hejr_nombre) ? $recorrer->rol->hejr_nombre : '' }}</td>
                                  <td>{{ $recorrer->name }}</td>
                                  <td>{{ $recorrer->email }}</td>
                                  <td>{{ $recorrer->dni }}</td>
                                  <td>{{ $recorrer->sexo }}</td>
                                  <td>{{ $recorrer->direccion }}</td>
                                  <td>{{ $recorrer->telefono }}</td>
                                  <td>{{ $recorrer->estado }}</td>
                                  <td><img src="{{ asset('storage'.'/'.$recorrer->foto) }}" width="50" class="img-thumbnail"></td>
                                  <td>
                                      <form action="{{ route('usuario.destroy',$recorrer->id) }}" method="post">
                                          @csrf
                                          @method('DELETE')
                                            <button class="btn btn-danger btn-icon" onclick="return confirm('Desea Eliminar?')"><i class="fa fa-times-circle"></i></button>
                                      </form> 
                                      
                                  </td>
                                  <td>  
                                   

                                  
                                 
                                      <a class="btn btn-info btn-icon" href="{{ route('usuario.edit',$recorrer->id) }}"><i class="fa fa-pen-square"></i></a>
                                  </td>

                              </tr>
                              @endforeach
                    </tbody>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
         
       

 
		

@endsection