routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
      return view('auth.login');
});

Auth::routes([
	'register' => false,
	
]);

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('rol','RolController');
Route::resource('autor','AutorController');
Route::resource('editorial','EditorialController');
Route::resource('libro','LibroController');
Route::resource('/usuario','UsuarioController');
Route::post('/porcentajea','PorcentajeController@aumentar')->name('porcentaje.aumentar');
Route::post('/porcentajed','PorcentajeController@disminuir')->name('porcentaje.disminuir');
Route::resource('aumentaindividual','AumentaController')->except(['create','store','destroy','show']);
Route::resource('restaindividual','RestaController')->except(['create','store','destroy','show']);

resources/views/editoriales/create.blade.php
@extends('layouts.template')

@section('titulo')
	Mantenimiento de Editoriales
@endsection

@section('content')

        <div class="col-lg-12 ">
              <div class="panel">
                  <div class="panel-heading">
                      <h3 class="panel-title bg-warning">Agregar Informacion de la Editorial</h3>
                  </div>
      
      
                  <!-- BASIC FORM ELEMENTS -->
                  <!--===================================================-->
               <form action="{{ route('editorial.store') }}" onsubmit="return validacionEditorial()" method="post" class="panel-body form-horizontal form-padding">
                        @csrf
                        <!--Static-->
                        @include('editoriales.form',['mensaje'=> 'crear'])
                                    
                     </form>
                  <!--===================================================-->
                  <!-- END BASIC FORM ELEMENTS -->
      
      
              </div>
          </div>
       

 
		

@endsection

resources/views/editoriales/edit.blade.php
@extends('layouts.template')

@section('titulo')
	Mantenimiento de Editoriales
@endsection

@section('content')

      <div class="col-lg-12 ">
              <div class="panel">
                  <div class="panel-heading">
                      <h3 class="panel-title">Editar Informacion de la Editorial</h3>
                  </div>
      
      
                  <!-- BASIC FORM ELEMENTS -->
                  <!--===================================================-->
                  <form  action="{{ route('editorial.update', $actualizar->id) }}" method="post" class="panel-body form-horizontal form-padding">
                    @csrf
                    @method('PUT')
      
                                 <div class="form-group">
                    <label class="col-md-3 control-label" for="demo-text-input">Nombre Editorial</label>
                        <div class="col-md-9">
                            <input type="text" id="editorial" name="hejr_nombre" value="{{ isset($actualizar->hejr_nombre) ? $actualizar->hejr_nombre : '' }}" id="demo-text-input" class="form-control" placeholder="Ingrese nombre editorial">
                            @error('hejr_nombre')
                            <small class="help-block text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                    </div>
    
                  

                     <div class="form-group">
                        <label class="col-md-3 control-label" for="demo-text-input">Email</label>
                        <div class="col-md-9">
                            <input type="text" id="email" name="hejr_email" value="{{ isset($actualizar->hejr_email) ? $actualizar->hejr_email : ''  }}"   id="demo-text-input" class="form-control" placeholder="Ingrese Email">
                            @error('hejr_email')
                            <small class="help-block text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-3 control-label" for="demo-email-input">Estado</label>
                        <div class="col-md-9">
                            <select name="hejr_estado" class="form-control">
                              <option>Seleccion de estado</option>  
                              <option value="A" @if($actualizar->hejr_estado == 'A') selected=""  @endif) >Activo</option>
                              <option value="I" @if($actualizar->hejr_estado == 'I') selected=""  @endif) >Inactivo</option>
                            </select>
                            @error('hejr_estado')
                            <small class="help-block text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                    </div>
          
                        
          
                        
          
                        
                         
           <div class="modal-footer">
                      <a href="{{ route('editorial.index') }}" class="btn btn-default" type="button">Close</a>
                      <input type="submit" class="btn btn-primary"  onclick="return confirm('Desea Actualizar?')" value="Actualizar Editorial" name="">
                    
                   </div>
          </form>
                  <!--===================================================-->
                  <!-- END BASIC FORM ELEMENTS -->
      
      
              </div>
          </div>
       

 
		

@endsection

resources/views/editoriales/form.blade.php
	 <div class="form-group">
        <label class="col-md-3 control-label" for="demo-text-input">Nombre Editorial</label>
            <div class="col-md-9">
                <input type="text" id="editorial" value="{{ old('hejr_nombre') }}" name="hejr_nombre"  id="demo-text-input" class="form-control" placeholder="Debe Comenzar por la primera letra Mayuscula">
                @error('hejr_nombre')
                <small class="help-block text-danger">{{ $message }}</small>
                @enderror
            </div>
        </div>

     
    <div class="form-group">
            <label class="col-md-3 control-label" for="demo-text-input">Email</label>
            <div class="col-md-9">
                <input type="text" id="email" value="{{ old('hejr_email') }}" name="hejr_email"    id="demo-text-input" class="form-control" placeholder="Ingrese Email">
                @error('hejr_email')
                <small class="help-block text-danger">{{ $message }}</small>
                @enderror
            </div>
    </div>
	
	              
	
	              
	
	              
	               
	 <div class="modal-footer">
        <a href="{{ route('editorial.index') }}" class="btn btn-default" type="button">Close</a>
        <input type="submit" class="btn btn-primary"  onclick="return confirm('Desea Agregar?')" value="Crear Editorial" name="">
    
	 </div>

resources/views/editoriales/index.blade.php
@extends('layouts.template')

@section('titulo')
	Mantenimiento de Editoriales
@endsection

@section('content')

		
	 <div class="col-12">
          
            <!-- /.card -->

            <div class="card">
              <div class="card-header">
               <a href="{{ route('editorial.create') }}"  class="btn btn-warning btn-rounded" style="color:white;">Agregar</a>

                @if(Session::has('Mensaje'))  
                  <div class="alert alert-info alert-dismissible mt-3">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    <h5><i class="icon fas fa-info"></i> Alert!</h5>
                    {{ Session::get('Mensaje') }}
                  </div>
                @endif
                
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table id="example1" class="table table-bordered table-striped">
                  <thead>
                  <tr>
                      <th> Editorial</th>                                 
                      <th >Email</th>
                      <th >Estado</th>
                      <th>Eliminar</th>
                      <th>Editar</th>
                   
                      
                  </tr>
                  </thead>
              
                    <tbody>
                        @foreach($leer as $recorrer)
                        <tr>
                            <td>{{ $recorrer->hejr_nombre }}</td>
                            <td>{{ $recorrer->hejr_email }}</td>
                            <td>{{ $recorrer->hejr_estado }}</td>
                            <td>
                                <form action="{{ route('editorial.destroy',$recorrer->id) }}" method="post">
                                    @csrf
                                    @method('DELETE')
                                      <button class="btn btn-danger btn-icon" onclick="return confirm('Desea Eliminar?')"><i class="fa fa-times-circle"></i></button>
                                </form> 
                                
                            </td>
                            <td>  
                             

                            
                           
                                <a class="btn btn-info btn-icon" href="{{ route('editorial.edit',$recorrer->id) }}"><i class="fa fa-pen-square"></i></a>
                            </td>

                        </tr>
                        @endforeach
                    </tbody>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
         
       

 
		

@endsection